// Generated by scripts/prepare-demo-news.mjs from real frozen-model inference.
import "server-only";

import type { AIAnalysisResult } from "@/app/api/ai-feedback/repositories/ai-analysis-service.interface";
import type { INewsArticle } from "@/lib/news/types";
import type { NewsInsightsAnalysis } from "@/lib/news-insights/types";
import type { MLTargetType } from "@/server/shared/database/schemas/enums";

export interface DemoNewsFixture {
  id: string;
  article: INewsArticle;
  targetClassification: MLTargetType;
  prediction: AIAnalysisResult;
  insights: NewsInsightsAnalysis;
  explanation: string;
  sourceUrl: string | null;
  capturedAt: string;
  bodySha256: string;
}

export const demoNewsFixtures: DemoNewsFixture[] = [
  {
    id: "3ba0e68e-30b2-4a26-8921-2d17c4e40101",
    article: {
      title: "Gato é 'preso' suspeito de furto nos EUA",
      description: "Policiais atenderam um chamado na Flórida e encontraram um gato perdido.",
      url: "https://g1.globo.com/planeta-bizarro/noticia/2019/09/04/gato-e-preso-suspeito-de-furto-nos-eua.ghtml",
      publishedAt: "2019-09-04T00:00:00-03:00",
      publisher: "G1 — Planeta Bizarro",
      content:
        "Policiais foram atender a um chamado por furto no estado americano da Flórida e acabaram encontrando um gato. O caso ocorreu no condado de Collier, na noite de domingo, 1º de setembro de 2019. Quatro agentes foram à casa depois que barulhos fizeram os moradores suspeitar de um furto. O animal foi levado a um abrigo. A identificação por microchip mostrou que ele se chamava Bones e havia fugido. Depois, o gato foi devolvido ao dono.",
      imageUrl:
        "https://s2-g1.glbimg.com/9CA_0YJ7llAixTf8koVJVjyzu6Q=/0x0:1700x2267/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2019/B/q/3X8o6MT8AhXgnuxP01bQ/gato.jpg",
      canonicalUrl:
        "https://g1.globo.com/planeta-bizarro/noticia/2019/09/04/gato-e-preso-suspeito-de-furto-nos-eua.ghtml",
      authors: [],
      modifiedAt: null,
      language: "pt-BR",
      extractionMethod: "local",
      usedFallback: false,
    },
    targetClassification: "reliable",
    prediction: {
      analysisStatus: "ok",
      classification: "reliable",
      fakeProbability: 0.19886002836551395,
      fakeScore: 19.886002836551395,
      scoreKind: "predicted_fake_probability",
      modelVersion: "svm-spacy-chi2k10k-svd500-v1",
      policyVersion: "olimpo-decision-policy-v1",
      artifactSha256: "123763864725531f12aa0503530edce432ca6e59853d36ef472559790207df27",
      inferenceVersion: "1b552c7bd1a07e12e6323c50f1a81e8095f3a6cf326ea01394f4af6a94b6b97b",
      reasons: [
        "Termos associados a notícias verdadeiras no corpus de treino que influenciaram a previsão: 'domingo', 'ao', 'no'.",
        "Característica da escrita: muitos substantivos.",
      ],
      inputScope: {
        source: "article_body",
        wordLimit: 100,
        analyzedWordCount: 76,
        truncated: false,
      },
    },
    insights: {
      analysisStatus: "ok",
      catalogVersion: "sintaxe-ampliada-descriptive-comparison-v3",
      extractorVersion: "collected-features-v1/spacy-3.8.16/pt_core_news_sm-3.8.0",
      analyzedText:
        "Policiais foram atender a um chamado por furto no estado americano da Flórida e acabaram encontrando um gato. O caso ocorreu no condado de Collier, na noite de domingo, 1o de setembro de 2019. Quatro agentes foram à casa depois que barulhos fizeram os moradores suspeitar de um furto. O animal foi le",
      characterLimit: 300,
      quality: {
        empty: false,
        noEligibleTokens: false,
        truncated: true,
      },
      insights: [
        {
          patternId: "8715ac5b8fc2",
          observationTitle: "Pronomes e descrições ligadas a nomes",
          observation:
            "Neste trecho, a leitura automática não encontrou descrições como “a pessoa que chegou” nem pronomes como “ele” ou “ela”.",
          reflectionQuestions: [],
          redundancyFamily: "referenciacao",
          measurements: [
            {
              feature: "DEP_acl:relcl_rate",
              label: "orações relativas",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 53,
              displayLabel:
                "descrições ligadas a nomes, como 'que chegou' em 'a pessoa que chegou'",
              displayText:
                "descrições ligadas a nomes, como 'que chegou' em 'a pessoa que chegou': 0 ocorrências identificadas",
            },
            {
              feature: "POS_PRON_rate",
              label: "pronomes",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 53,
              displayLabel: "pronomes, como 'ele', 'ela' e 'isso'",
              displayText: "pronomes, como 'ele', 'ela' e 'isso': 0 ocorrências identificadas",
            },
          ],
          comparison: {
            kind: "descriptive_corpus_frequency",
            referenceDataset: "Fake.br-Corpus",
            partition: "validation",
            authorScope: "all",
            sourceRun: "fp-growth-metadados-ampliados-20261008T002311Z",
            variant: "sintaxe_ampliada",
            scope: "matched_pattern",
            fake: {
              count: 185,
              total: 720,
              frequency: 0.2569444444444444,
            },
            true: {
              count: 256,
              total: 720,
              frequency: 0.35555555555555557,
            },
          },
        },
        {
          patternId: "d1280945c7ef",
          observationTitle: "Quem realiza ou recebe a ação",
          observation:
            "Neste trecho, a leitura automática não encontrou referências como “a proposta” em “a proposta foi aprovada”; encontrou 5 referências a quem age, como “a equipe” em “a equipe publicou” (proporção na faixa mais alta da referência).",
          reflectionQuestions: [],
          redundancyFamily: "agentes",
          measurements: [
            {
              feature: "DEP_nsubj:pass_rate",
              label: "sujeitos de construções passivas",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 53,
              displayLabel:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada'",
              displayText:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada': 0 ocorrências identificadas",
            },
            {
              feature: "DEP_nsubj_rate",
              label: "sujeitos nominais",
              value: 0.09433962264150944,
              operator: ">=",
              threshold: 0.09090909090909091,
              denominator: "tokens_lexical",
              count: 5,
              denominatorCount: 53,
              displayLabel: "referências a quem age, como 'a equipe' em 'a equipe publicou'",
              displayText:
                "referências a quem age, como 'a equipe' em 'a equipe publicou': 5 ocorrências identificadas; proporção na faixa superior da referência estudada",
            },
          ],
          comparison: {
            kind: "descriptive_corpus_frequency",
            referenceDataset: "Fake.br-Corpus",
            partition: "validation",
            authorScope: "all",
            sourceRun: "fp-growth-metadados-ampliados-20261008T002311Z",
            variant: "sintaxe_ampliada",
            scope: "matched_pattern",
            fake: {
              count: 195,
              total: 720,
              frequency: 0.2708333333333333,
            },
            true: {
              count: 157,
              total: 720,
              frequency: 0.21805555555555556,
            },
          },
        },
        {
          patternId: "9865be178551",
          observationTitle: "Palavras de ligação e afirmações ligadas a verbos",
          observation:
            "Neste trecho, a leitura automática não encontrou afirmações como “o prazo acabou” em “disse que o prazo acabou”; encontrou 12 palavras de ligação como “de”, “em” ou “para” (proporção na faixa mais alta da referência).",
          reflectionQuestions: [],
          redundancyFamily: "contexto",
          measurements: [
            {
              feature: "DEP_ccomp_rate",
              label: "complementos oracionais",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 53,
              displayLabel:
                "afirmações ligadas a um verbo, como 'o prazo acabou' em 'disse que o prazo acabou'",
              displayText:
                "afirmações ligadas a um verbo, como 'o prazo acabou' em 'disse que o prazo acabou': 0 ocorrências identificadas",
            },
            {
              feature: "POS_ADP_rate",
              label: "preposições",
              value: 0.22641509433962265,
              operator: ">=",
              threshold: 0.22448979591836735,
              denominator: "tokens_lexical",
              count: 12,
              denominatorCount: 53,
              displayLabel: "palavras de ligação, como 'de', 'em' e 'para'",
              displayText:
                "palavras de ligação, como 'de', 'em' e 'para': 12 ocorrências identificadas; proporção na faixa superior da referência estudada",
            },
          ],
          comparison: {
            kind: "descriptive_corpus_frequency",
            referenceDataset: "Fake.br-Corpus",
            partition: "validation",
            authorScope: "all",
            sourceRun: "fp-growth-metadados-ampliados-20261008T002311Z",
            variant: "sintaxe_ampliada",
            scope: "matched_pattern",
            fake: {
              count: 74,
              total: 720,
              frequency: 0.10277777777777777,
            },
            true: {
              count: 190,
              total: 720,
              frequency: 0.2638888888888889,
            },
          },
        },
      ],
    },
    explanation:
      "Verdadeira. A expressão 'preso' é figurada: o gato Bones foi encontrado pelos policiais, identificado pelo microchip e devolvido ao dono. Este é um resumo preparado para o desafio, baseado na reportagem indicada e corroborado pela reprodução da notícia em uma prova oficial da Prefeitura de Bauru.",
    sourceUrl:
      "https://g1.globo.com/planeta-bizarro/noticia/2019/09/04/gato-e-preso-suspeito-de-furto-nos-eua.ghtml",
    capturedAt: "2026-10-08T20:37:00.190Z",
    bodySha256: "e9359215ddb0d46c9b2abdfacf79e3899bfe0e0d30366d9ea0fbfe9b1663318a",
  },
  {
    id: "3ba0e68e-30b2-4a26-8921-2d17c4e40102",
    article: {
      title: "Santa Aurora testa calçada que recarrega celulares com os passos dos pedestres",
      description:
        "Placas no passeio alimentam entradas USB; projeto promete carga completa após quarenta passos.",
      url: "https://santa-aurora.example/noticias/calcada-energia",
      publishedAt: "2026-10-08T09:00:00-03:00",
      publisher: "Jornal de Santa Aurora",
      content:
        "Você já imaginou carregar o celular enquanto caminha? Essa ideia acaba de se tornar realidade em Santa Aurora. Uma calçada inteligente promete carga completa com apenas quarenta passos, sem precisar de tomada. A tecnologia usa placas que aproveitam a pressão dos pés e envia a energia diretamente para entradas USB. Segundo os responsáveis, o sistema vai acabar com a falta de bateria nas ruas. Agora qualquer pessoa pode obter energia gratuita, mesmo sem sol. Os testes começam amanhã e os moradores já comemoram a novidade.",
      imageUrl: "/demo/challenge-street.png",
      canonicalUrl: "https://santa-aurora.example/noticias/calcada-energia",
      authors: [],
      modifiedAt: null,
      language: "pt-BR",
      extractionMethod: "local",
      usedFallback: false,
    },
    targetClassification: "unreliable",
    prediction: {
      analysisStatus: "ok",
      classification: "unreliable",
      fakeProbability: 0.779352080600847,
      fakeScore: 77.9352080600847,
      scoreKind: "predicted_fake_probability",
      modelVersion: "svm-spacy-chi2k10k-svd500-v1",
      policyVersion: "olimpo-decision-policy-v1",
      artifactSha256: "123763864725531f12aa0503530edce432ca6e59853d36ef472559790207df27",
      inferenceVersion: "1b552c7bd1a07e12e6323c50f1a81e8095f3a6cf326ea01394f4af6a94b6b97b",
      reasons: [
        "Termos associados a notícias falsas no corpus de treino que influenciaram a previsão: 'acabar', 'pode', 'uma'.",
        "Característica da escrita: uso alto de artigos/determinantes.",
        "Característica da escrita: poucas preposições.",
      ],
      inputScope: {
        source: "article_body",
        wordLimit: 100,
        analyzedWordCount: 85,
        truncated: false,
      },
    },
    insights: {
      analysisStatus: "ok",
      catalogVersion: "sintaxe-ampliada-descriptive-comparison-v3",
      extractorVersion: "collected-features-v1/spacy-3.8.16/pt_core_news_sm-3.8.0",
      analyzedText:
        "Você já imaginou carregar o celular enquanto caminha? Essa ideia acaba de se tornar realidade em Santa Aurora. Uma calçada inteligente promete carga completa com apenas quarenta passos, sem precisar de tomada. A tecnologia usa placas que aproveitam a pressão dos pés e envia a energia diretamente par",
      characterLimit: 300,
      quality: {
        empty: false,
        noEligibleTokens: false,
        truncated: true,
      },
      insights: [
        {
          patternId: "8c3cebc0601d",
          observationTitle: "Verbos de apoio e quem recebe a ação",
          observation:
            "Neste trecho, a leitura automática não encontrou referências como “a proposta” em “a proposta foi aprovada” nem verbos de apoio como “foi” em “foi aprovado”.",
          reflectionQuestions: [],
          redundancyFamily: "construcoes_verbais",
          measurements: [
            {
              feature: "DEP_nsubj:pass_rate",
              label: "sujeitos de construções passivas",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 48,
              displayLabel:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada'",
              displayText:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada': 0 ocorrências identificadas",
            },
            {
              feature: "POS_AUX_rate",
              label: "verbos auxiliares",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 48,
              displayLabel: "verbos de apoio, como 'foi' em 'foi aprovado'",
              displayText:
                "verbos de apoio, como 'foi' em 'foi aprovado': 0 ocorrências identificadas",
            },
          ],
          comparison: {
            kind: "descriptive_corpus_frequency",
            referenceDataset: "Fake.br-Corpus",
            partition: "validation",
            authorScope: "all",
            sourceRun: "fp-growth-metadados-ampliados-20261008T002311Z",
            variant: "sintaxe_ampliada",
            scope: "matched_pattern",
            fake: {
              count: 145,
              total: 720,
              frequency: 0.2013888888888889,
            },
            true: {
              count: 242,
              total: 720,
              frequency: 0.33611111111111114,
            },
          },
        },
        {
          patternId: "d1280945c7ef",
          observationTitle: "Quem realiza ou recebe a ação",
          observation:
            "Neste trecho, a leitura automática não encontrou referências como “a proposta” em “a proposta foi aprovada”; encontrou 5 referências a quem age, como “a equipe” em “a equipe publicou” (proporção na faixa mais alta da referência).",
          reflectionQuestions: [],
          redundancyFamily: "agentes",
          measurements: [
            {
              feature: "DEP_nsubj:pass_rate",
              label: "sujeitos de construções passivas",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 48,
              displayLabel:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada'",
              displayText:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada': 0 ocorrências identificadas",
            },
            {
              feature: "DEP_nsubj_rate",
              label: "sujeitos nominais",
              value: 0.10416666666666667,
              operator: ">=",
              threshold: 0.09090909090909091,
              denominator: "tokens_lexical",
              count: 5,
              denominatorCount: 48,
              displayLabel: "referências a quem age, como 'a equipe' em 'a equipe publicou'",
              displayText:
                "referências a quem age, como 'a equipe' em 'a equipe publicou': 5 ocorrências identificadas; proporção na faixa superior da referência estudada",
            },
          ],
          comparison: {
            kind: "descriptive_corpus_frequency",
            referenceDataset: "Fake.br-Corpus",
            partition: "validation",
            authorScope: "all",
            sourceRun: "fp-growth-metadados-ampliados-20261008T002311Z",
            variant: "sintaxe_ampliada",
            scope: "matched_pattern",
            fake: {
              count: 195,
              total: 720,
              frequency: 0.2708333333333333,
            },
            true: {
              count: 157,
              total: 720,
              frequency: 0.21805555555555556,
            },
          },
        },
        {
          patternId: "8b970151f163",
          observationTitle: "A quem ou a que as ações se dirigem",
          observation:
            "Neste trecho, a leitura automática não encontrou referências como “a proposta” em “a proposta foi aprovada”; encontrou 7 alvos da ação, como “o relatório” em “publicou o relatório” (proporção na faixa mais alta da referência).",
          reflectionQuestions: [],
          redundancyFamily: "objetos",
          measurements: [
            {
              feature: "DEP_nsubj:pass_rate",
              label: "sujeitos de construções passivas",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 48,
              displayLabel:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada'",
              displayText:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada': 0 ocorrências identificadas",
            },
            {
              feature: "DEP_obj_rate",
              label: "objetos diretos",
              value: 0.14583333333333334,
              operator: ">=",
              threshold: 0.08163265306122448,
              denominator: "tokens_lexical",
              count: 7,
              denominatorCount: 48,
              displayLabel:
                "referências ao alvo da ação, como 'o relatório' em 'publicou o relatório'",
              displayText:
                "referências ao alvo da ação, como 'o relatório' em 'publicou o relatório': 7 ocorrências identificadas; proporção na faixa superior da referência estudada",
            },
          ],
          comparison: {
            kind: "descriptive_corpus_frequency",
            referenceDataset: "Fake.br-Corpus",
            partition: "validation",
            authorScope: "all",
            sourceRun: "fp-growth-metadados-ampliados-20261008T002311Z",
            variant: "sintaxe_ampliada",
            scope: "matched_pattern",
            fake: {
              count: 211,
              total: 720,
              frequency: 0.29305555555555557,
            },
            true: {
              count: 133,
              total: 720,
              frequency: 0.18472222222222223,
            },
          },
        },
      ],
    },
    explanation:
      "Falsa. A cidade, o veículo, o projeto e a notícia foram inventados exclusivamente para este desafio educativo. A imagem é sintética e não documenta um evento real. Embora pavimentos possam captar pequenas quantidades de energia dos passos, isso não comprova a promessa apresentada. O texto foi escolhido após testar variantes no modelo real; o resultado salvo não foi alterado. Aparência jornalística e fotografia convincente não substituem uma fonte verificável.",
    sourceUrl: null,
    capturedAt: "2026-10-08T20:37:00.190Z",
    bodySha256: "800299a99a947467822dc2575888bffeaa182e201122ced1dcc29cc11ac99fbf",
  },
  {
    id: "3ba0e68e-30b2-4a26-8921-2d17c4e40103",
    article: {
      title: "Incêndio atinge prédio da Universidade Federal de Pernambuco",
      description: "Bombeiros enviaram cinco viaturas ao campus do Recife; não houve feridos.",
      url: "https://g1.globo.com/pe/pernambuco/noticia/2026/10/07/incendio-predio-da-ufpe-video.ghtml",
      publishedAt: "2026-10-07T00:00:00-03:00",
      publisher: "G1 — Pernambuco",
      content:
        "Um incêndio atingiu um prédio da Universidade Federal de Pernambuco na noite de quarta-feira, 7 de outubro de 2026, no campus do Recife. O Corpo de Bombeiros enviou cinco viaturas para combater o fogo. Segundo a corporação, ninguém ficou ferido. O prédio abrigava laboratórios de pesquisa e ficava perto da Casa do Estudante, na Cidade Universitária. A universidade informou que os produtos armazenados no local contribuíram para a propagação das chamas e que os danos seriam avaliados. As atividades acadêmicas de quinta-feira foram mantidas.",
      imageUrl: null,
      canonicalUrl:
        "https://g1.globo.com/pe/pernambuco/noticia/2026/10/07/incendio-predio-da-ufpe-video.ghtml",
      authors: [],
      modifiedAt: null,
      language: "pt-BR",
      extractionMethod: "local",
      usedFallback: false,
    },
    targetClassification: "reliable",
    prediction: {
      analysisStatus: "ok",
      classification: "reliable",
      fakeProbability: 0.011449677334930804,
      fakeScore: 1.1449677334930803,
      scoreKind: "predicted_fake_probability",
      modelVersion: "svm-spacy-chi2k10k-svd500-v1",
      policyVersion: "olimpo-decision-policy-v1",
      artifactSha256: "123763864725531f12aa0503530edce432ca6e59853d36ef472559790207df27",
      inferenceVersion: "1b552c7bd1a07e12e6323c50f1a81e8095f3a6cf326ea01394f4af6a94b6b97b",
      reasons: [
        "Termos associados a notícias verdadeiras no corpus de treino que influenciaram a previsão: 'feira', 'cinco', 'quinta'.",
        "Característica da escrita: muitas preposições (estilo nominal).",
      ],
      inputScope: {
        source: "article_body",
        wordLimit: 100,
        analyzedWordCount: 84,
        truncated: false,
      },
    },
    insights: {
      analysisStatus: "ok",
      catalogVersion: "sintaxe-ampliada-descriptive-comparison-v3",
      extractorVersion: "collected-features-v1/spacy-3.8.16/pt_core_news_sm-3.8.0",
      analyzedText:
        "Um incêndio atingiu um prédio da Universidade Federal de Pernambuco na noite de quarta-feira, 7 de outubro de 2026, no campus do Recife. O Corpo de Bombeiros enviou cinco viaturas para combater o fogo. Segundo a corporação, ninguém ficou ferido. O prédio abrigava laboratórios de pesquisa e ficava pe",
      characterLimit: 300,
      quality: {
        empty: false,
        noEligibleTokens: false,
        truncated: true,
      },
      insights: [
        {
          patternId: "afaef19656e5",
          observationTitle: "Palavras que detalham as ações",
          observation:
            "Neste trecho, a leitura automática não encontrou detalhes como “rapidamente” em “chegou rapidamente” nem palavras como “hoje”, “aqui” ou “rapidamente”.",
          reflectionQuestions: [],
          redundancyFamily: "modificacao_adverbial",
          measurements: [
            {
              feature: "DEP_advmod_rate",
              label: "modificadores adverbiais",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 49,
              displayLabel:
                "palavras que detalham uma ação ou qualidade, como 'rapidamente' e 'muito'",
              displayText:
                "palavras que detalham uma ação ou qualidade, como 'rapidamente' e 'muito': 0 ocorrências identificadas",
            },
            {
              feature: "POS_ADV_rate",
              label: "advérbios",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 49,
              displayLabel: "advérbios, como 'hoje', 'aqui' e 'rapidamente'",
              displayText:
                "advérbios, como 'hoje', 'aqui' e 'rapidamente': 0 ocorrências identificadas",
            },
          ],
          comparison: {
            kind: "descriptive_corpus_frequency",
            referenceDataset: "Fake.br-Corpus",
            partition: "validation",
            authorScope: "all",
            sourceRun: "fp-growth-metadados-ampliados-20261008T002311Z",
            variant: "sintaxe_ampliada",
            scope: "matched_pattern",
            fake: {
              count: 149,
              total: 720,
              frequency: 0.20694444444444443,
            },
            true: {
              count: 267,
              total: 720,
              frequency: 0.37083333333333335,
            },
          },
        },
        {
          patternId: "8c3cebc0601d",
          observationTitle: "Verbos de apoio e quem recebe a ação",
          observation:
            "Neste trecho, a leitura automática não encontrou referências como “a proposta” em “a proposta foi aprovada” nem verbos de apoio como “foi” em “foi aprovado”.",
          reflectionQuestions: [],
          redundancyFamily: "construcoes_verbais",
          measurements: [
            {
              feature: "DEP_nsubj:pass_rate",
              label: "sujeitos de construções passivas",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 49,
              displayLabel:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada'",
              displayText:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada': 0 ocorrências identificadas",
            },
            {
              feature: "POS_AUX_rate",
              label: "verbos auxiliares",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 49,
              displayLabel: "verbos de apoio, como 'foi' em 'foi aprovado'",
              displayText:
                "verbos de apoio, como 'foi' em 'foi aprovado': 0 ocorrências identificadas",
            },
          ],
          comparison: {
            kind: "descriptive_corpus_frequency",
            referenceDataset: "Fake.br-Corpus",
            partition: "validation",
            authorScope: "all",
            sourceRun: "fp-growth-metadados-ampliados-20261008T002311Z",
            variant: "sintaxe_ampliada",
            scope: "matched_pattern",
            fake: {
              count: 145,
              total: 720,
              frequency: 0.2013888888888889,
            },
            true: {
              count: 242,
              total: 720,
              frequency: 0.33611111111111114,
            },
          },
        },
        {
          patternId: "8b970151f163",
          observationTitle: "A quem ou a que as ações se dirigem",
          observation:
            "Neste trecho, a leitura automática não encontrou referências como “a proposta” em “a proposta foi aprovada”; encontrou 5 alvos da ação, como “o relatório” em “publicou o relatório” (proporção na faixa mais alta da referência).",
          reflectionQuestions: [],
          redundancyFamily: "objetos",
          measurements: [
            {
              feature: "DEP_nsubj:pass_rate",
              label: "sujeitos de construções passivas",
              value: 0,
              operator: "<=",
              threshold: 0,
              denominator: "tokens_lexical",
              count: 0,
              denominatorCount: 49,
              displayLabel:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada'",
              displayText:
                "referências a quem recebe a ação, como 'a proposta' em 'a proposta foi aprovada': 0 ocorrências identificadas",
            },
            {
              feature: "DEP_obj_rate",
              label: "objetos diretos",
              value: 0.10204081632653061,
              operator: ">=",
              threshold: 0.08163265306122448,
              denominator: "tokens_lexical",
              count: 5,
              denominatorCount: 49,
              displayLabel:
                "referências ao alvo da ação, como 'o relatório' em 'publicou o relatório'",
              displayText:
                "referências ao alvo da ação, como 'o relatório' em 'publicou o relatório': 5 ocorrências identificadas; proporção na faixa superior da referência estudada",
            },
          ],
          comparison: {
            kind: "descriptive_corpus_frequency",
            referenceDataset: "Fake.br-Corpus",
            partition: "validation",
            authorScope: "all",
            sourceRun: "fp-growth-metadados-ampliados-20261008T002311Z",
            variant: "sintaxe_ampliada",
            scope: "matched_pattern",
            fake: {
              count: 211,
              total: 720,
              frequency: 0.29305555555555557,
            },
            true: {
              count: 133,
              total: 720,
              frequency: 0.18472222222222223,
            },
          },
        },
      ],
    },
    explanation:
      "Verdadeira. O incêndio no campus Recife da UFPE em 7 de outubro de 2026 foi noticiado por vários veículos. Este é um resumo preparado para o desafio, com informações corroboradas pela cobertura do ocorrido. O link indicado permite conferir a reportagem; a previsão da IA considera somente o texto resumido exibido, não a origem ou o link.",
    sourceUrl:
      "https://g1.globo.com/pe/pernambuco/noticia/2026/10/07/incendio-predio-da-ufpe-video.ghtml",
    capturedAt: "2026-10-08T20:37:00.190Z",
    bodySha256: "f7598c6c9be8e4382528c34a1aa6d9c21939de4256a31021540907b5d7b62360",
  },
];

export function getDemoNewsFixture(id: string): DemoNewsFixture | undefined {
  return demoNewsFixtures.find((fixture) => fixture.id === id);
}
